/* 
  CLOUD_NOTE
  Unidad funcional que contiene 3 elementos principales (manera de representar un "documento" NoSQL):
  1. primary key of the NOTE in the DB (cloud). Unique ID generated by Firebase.
  2. the owner USER ID.
  3. text field. 
*/

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firstapp/services/cloud/cloud_storage_constants.dart';
import 'package:flutter/foundation.dart';

@immutable
class CloudNote {
  final String documentId;
  final String ownerUserId;
  final String text;

  const CloudNote({
    required this.documentId, 
    required this.ownerUserId, 
    required this.text,
  });

  //La info que nos llega de la BD Firestore nos viene en forma 
  //de un "Map" wrappeado dentro de un "QueryDocumentSnapshot".
  CloudNote.fromSnapshot(QueryDocumentSnapshot<Map<String, dynamic>> snapshot) :
    documentId = snapshot.id,
    ownerUserId = snapshot.data()[ownerUserIdFieldName],
    text = snapshot.data()[textFieldName] as String;
  
}